spring:
  r2dbc:
    name: psico-no-precinho-backend
    url: ${R2DBC_DATABASE_URL:r2dbc:pool:postgresql://localhost:5432/psiconoprecinho}
    schema: public
    username: ${DATABASE_USERNAME:application}
    password: ${DATABASE_PASSWORD:application}
    properties:
      sslMode: REQUIRE
    pool:
      initial-size: 20
      max-size: 20
      max-idle-time: 2m
      max-life-time: 30m
      validation-query: SELECT 1