spring:
  r2dbc:
    name: psico-no-precinho-backend
    url: ${R2DBC_DATABASE_URL}
    schema: public
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    properties:
      sslMode: REQUIRE
    pool:
      initial-size: 20
      max-size: 20
      max-idle-time: 2m
      max-life-time: 30m
      validation-query: SELECT 1