spring:
  r2dbc:
    name: psico-no-precinho-backend
    url: ${DATABASE_URL:r2dbc:pool:postgresql://localhost:5432/psiconoprecinho?currentSchema=public}
    username: ${DATABASE_USERNAME:application}
    password: ${DATABASE_PASSWORD:application}
    pool:
      initial-size: 20
      max-size: 20
      max-idle-time: 2m
      max-life-time: 30m
      validation-query: SELECT 1