logging.level.org.springframework.web: DEBUG

spring:
  server:
    port: 8082
  r2dbc:
    name: psiconoprecinho
    url: r2dbc:pool:mysql://localhost:3306/psiconoprecinho
    username: psiconoprecinho-app
    password: psiconoprecinho-app
    pool:
      initial-size: 20
      max-size: 20
      max-idle-time: 2m
      max-life-time: 30m
      validation-query: SELECT 1
  application: psiconoprecinho-app
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    serialization.WRITE_DATES_AS_TIMESTAMPS: false